---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
   VpcIpv4AddressBlock:
      Description: 'IPv4 address block to assign to the VPC in CIDR format.'
      Type: String
      AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
Resources:
   Vpc:
      Type: 'AWS::EC2::VPC'
      Properties:
         CidrBlock: !Ref VpcIpv4AddressBlock
   InternetGateway:
      Type: 'AWS::EC2::InternetGateway'
   InternetGatewayAttachment:
      Type: 'AWS::EC2::VPCGatewayAttachment'
      Properties:
         InternetGatewayId: !Ref InternetGateway
         VpcId: !Ref Vpc
   PublicSubnet:
      Type: 'AWS::EC2::Subnet'
      Properties:
         CidrBlock: !Select [ 1, !Cidr [ !GetAtt Vpc.CidrBlock, 2, 4 ] ]
         VpcId: !Ref Vpc
   PublicRouteTable:
      Type: 'AWS::EC2::RouteTable'
      Properties:
         VpcId: !Ref Vpc
   InternetRoute:
      Type: 'AWS::EC2::Route'
      Properties:
         RouteTableId: !Ref PublicRouteTable
         GatewayId: !Ref InternetGateway
         DestinationCidrBlock: '0.0.0.0/0'
      DependsOn: InternetGatewayAttachment
   PublicRouteTableAssociation:
      Type: 'AWS::EC2::SubnetRouteTableAssociation'
      Properties:
         RouteTableId: !Ref PublicRouteTable
         SubnetId: !Ref PublicSubnet
   NatGateway:
      Type: 'AWS::EC2::NatGateway'
      Properties:
         AllocationId: !GetAtt NatGatewayElasticIpAddress.AllocationId
         SubnetId: !Ref PublicSubnet
      DependsOn: InternetGatewayAttachment
   NatGatewayElasticIpAddress:
      Type: 'AWS::EC2::EIP'
      Properties:
         Domain: vpc
   PrivateSubnet:
      Type: 'AWS::EC2::Subnet'
      Properties:
         CidrBlock: !Select [ 0, !Cidr [ !GetAtt Vpc.CidrBlock, 2, 4 ] ]
         VpcId: !Ref Vpc
   PrivateRouteTable:
      Type: 'AWS::EC2::RouteTable'
      Properties:
         VpcId: !Ref Vpc
   NatRoute:
      Type: 'AWS::EC2::Route'
      Properties:
         RouteTableId: !Ref PrivateRouteTable
         NatGatewayId: !Ref NatGateway
         DestinationCidrBlock: '0.0.0.0/0'
      DependsOn: InternetGatewayAttachment
   PrivateRouteTableAssociation:
      Type: 'AWS::EC2::SubnetRouteTableAssociation'
      Properties:
         RouteTableId: !Ref PrivateRouteTable
         SubnetId: !Ref PrivateSubnet
   BuildRole:
      Type: 'AWS::IAM::Role'
      Properties:
         AssumeRolePolicyDocument:
            Version: '2012-10-17'
            Statement:
               -
                  Principal:
                     Service: 'codebuild.amazonaws.com'
                  Action: 'sts:AssumeRole'
                  Effect: Allow
         Policies:
            -
               PolicyName: ec2-codebuild
               PolicyDocument:
                  Version: '2012-10-17'
                  Statement:
                     -
                        Action:
                           - 'ec2:CreateNetworkInterface'
                           - 'ec2:DeleteNetworkInterface'
                           - 'ec2:DescribeDhcpOptions'
                           - 'ec2:DescribeNetworkInterfaces'
                           - 'ec2:DescribeSecurityGroups'
                           - 'ec2:DescribeSubnets'
                           - 'ec2:DescribeVpcs'
                        Resource: '*'
                        Effect: Allow
                     -
                        Action:
                           - 'ec2:CreateNetworkInterfacePermission'
                        Resource: !Sub 'arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:network-interface/*'
                        Condition:
                           StringEquals:
                              ec2:Subnet: !Sub 'arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:subnet/${PrivateSubnet}'
                              ec2:AuthorizedService: 'codebuild.amazonaws.com'
                        Effect: Allow
            -
               PolicyName: ecr-pull
               PolicyDocument:
                  Version: '2012-10-17'
                  Statement:
                     -
                        Action:
                           - 'ecr:GetDownloadUrlForLayer'
                           - 'ecr:BatchGetImage'
                           - 'ecr:BatchCheckLayerAvailability'
                        Resource: '*'
                        Effect: Allow
            -
               PolicyName: parameters
               PolicyDocument:
                  Version: '2012-10-17'
                  Statement:
                     -
                        Action:
                           - 'ssm:GetParameters'
                        Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/frontdoor/*'
                        Effect: Allow
            -
               PolicyName: packer
               PolicyDocument:
                  Version: '2012-10-17'
                  Statement:
                     -
                        Action:
                           - 'ec2:DescribeImages'
                        Resource: '*'
                        Effect: Allow
                     -
                        Action:
                           - 'ec2:RunInstances'
                        Resource:
                           - !Sub 'arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:image/*'
                           - !Sub 'arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:instance/*'
                           - !Sub 'arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:network-interface/*'
                           - !Sub 'arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:security-group/*'
                           - !Sub 'arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:subnet/*'
                           - !Sub 'arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:volume/*'
                        Condition:
                           StringEquals:
                              aws:RequestTag/Packer: frontdoor
                        Effect: Allow
                     -
                        Action:
                           - 'ec2:CreateTags'
                        Resource: !Sub 'arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:instance/*'
                        Condition:
                           StringEquals:
                              ec2:CreateAction: 'RunInstances'
                        Effect: "Allow"
                     -
                        Action:
                           - 'ec2:CreateVolume'
                        Resource: !Sub 'arn:aws:ec2:*:${AWS::AccountId}:volume/*'
                        Condition:
                           StringEquals:
                              aws:RequestTag/Packer: frontdoor
                        Effect: 'Allow'
                     -
                        Action:
                           - 'ec2:StopInstances'
                           - 'ec2:TerminateInstances'
                        Resource: !Sub 'arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:instance/*'
                        Condition:
                           StringEquals:
                              ec2:ResourceTag/Packer: frontdoor
                        Effect: Allow
                     -
                        Action:
                           - 'ec2:CreateImage'
                           - 'ec2:RegisterImage'
                        Resource: '*'
                        Effect: Allow
                     #-
                     #   Action:
                     #      - 'ec2:AttachVolume'
                     #      - 'ec2:AuthorizeSecurityGroupIngress'
                     #      - 'ec2:CopyImage'
                     #      - 'ec2:CreateImage'
                     #      - 'ec2:CreateKeypair'
                     #      - 'ec2:CreateSecurityGroup'
                     #      - 'ec2:CreateSnapshot'
                     #      - 'ec2:CreateTags'
                     #      - 'ec2:CreateVolume'
                     #      - 'ec2:DeleteKeyPair'
                     #      - 'ec2:DeleteSecurityGroup'
                     #      - 'ec2:DeleteSnapshot'
                     #      - 'ec2:DeleteVolume'
                     #      - 'ec2:DeregisterImage'
                     #      - 'ec2:DescribeImageAttribute'
                     #      - 'ec2:DescribeImages'
                     #      - 'ec2:DescribeInstances'
                     #      - 'ec2:DescribeRegions'
                     #      - 'ec2:DescribeSecurityGroups'
                     #      - 'ec2:DescribeSnapshots'
                     #      - 'ec2:DescribeSubnets'
                     #      - 'ec2:DescribeTags'
                     #      - 'ec2:DescribeVolumes'
                     #      - 'ec2:DetachVolume'
                     #      - 'ec2:GetPasswordData'
                     #      - 'ec2:ModifyImageAttribute'
                     #      - 'ec2:ModifyInstanceAttribute'
                     #      - 'ec2:ModifySnapshotAttribute'
                     #      - 'ec2:RegisterImage'
                     #   Resource: !Sub 'arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:volume/*'
                     #   Condition:
                     #      StringEquals:
                     #         ec2:ResourceTag/Packer: frontdoor
                     #   Effect: Allow
   BuildLogsPolicy:
      Type: 'AWS::IAM::Policy'
      Properties:
         PolicyName: logs
         PolicyDocument:
            Version: '2012-10-17'
            Statement:
               -
                  Action:
                     - 'logs:CreateLogGroup'
                     - 'logs:CreateLogStream'
                     - 'logs:PutLogEvents'
                  Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${BuildProject}:*'
                  Effect: Allow
         Roles:
            - !Ref BuildRole
   ContainerSecurityGroup:
      Type: 'AWS::EC2::SecurityGroup'
      Properties:
         GroupDescription: 'Music AMI build container.'
         VpcId: !Ref Vpc
   InstanceSecurityGroup:
      Type: 'AWS::EC2::SecurityGroup'
      Properties:
         GroupDescription: 'Music AMI build instance.'
         SecurityGroupIngress:
            -
               SourceSecurityGroupId: !GetAtt ContainerSecurityGroup.GroupId
               FromPort: 22
               ToPort: 22
               IpProtocol: tcp
         VpcId: !Ref Vpc
   BuildProject:
      Type: 'AWS::CodeBuild::Project'
      Properties:
         Name: frontdoor-ami
         Description: 'AWS EC2 Frontdoor AMI build'
         ServiceRole: !GetAtt BuildRole.Arn
         Source:
            Type: GITHUB
            Location: 'https://github.com/kalrish/aws-ec2-frontdoor.git'
            GitCloneDepth: 1
            BuildSpec: 'buildspec.yaml'
         Environment:
            Type: LINUX_CONTAINER
            ComputeType: BUILD_GENERAL1_SMALL
            Image: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/ami-build-env'
            PrivilegedMode: false
            EnvironmentVariables:
               -
                  Name: VPC
                  Type: PLAINTEXT
                  Value: !Ref Vpc
               -
                  Name: SUBNET
                  Type: PLAINTEXT
                  Value: !Ref PrivateSubnet
               -
                  Name: SECURITY_GROUP_INSTANCE
                  Type: PLAINTEXT
                  Value: !GetAtt InstanceSecurityGroup.GroupId
         Artifacts:
            Type: NO_ARTIFACTS
         VpcConfig:
            VpcId: !Ref Vpc
            Subnets:
               - !Ref PrivateSubnet
            SecurityGroupIds:
               - !GetAtt ContainerSecurityGroup.GroupId
