---
- name: Update system software
  pacman:
     update_cache: yes
     upgrade: yes
- name: Install required packages
  pacman:
     name: '{{ item }}'
     state: present
  with_items:
     - openssh
- name: Upload SSH server configuration
  copy:
     src: sshd_config
     dest: /etc/ssh/sshd_config
